version: 2
updates:
# Weekly version updates.
- package-ecosystem: "pip"
  directory: "/"
  schedule:
    interval: "weekly"
  groups:
    patches-and-minor-upgrades:
      update-types:
        - "minor"
        - "patch"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
  groups:
    patches-and-minor-upgrades:
      update-types:
        - "minor"
        - "patch"
