language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install .
  - pip install -r requirements.txt
script: coverage run setup.py test
after_success: coveralls
deploy:
  provider: pypi
  user: "$PYPI_USERNAME"
  password: "$PYPI_PASSWORD"
  on:
    tags: true
